# ------------------------------------------------------------
# Custom BoT-SORT tracker for entrance/exit people counting
# ------------------------------------------------------------

tracker_type: botsort # (str) Tracker backend: botsort|bytetrack; choose botsort to enable BoT-SORT features
track_high_thresh: 0.25 # (float) First-stage match threshold; raise for cleaner tracks, lower to keep more
track_low_thresh: 0.1 # (float) Second-stage threshold for low-score matches; balances recovery vs drift
new_track_thresh: 0.25 # (float) Start a new track if no match ≥ this; higher reduces false tracks
track_buffer: 60 # (int) Frames to keep lost tracks alive; higher handles occlusion, increases ID switches risk
match_thresh: 0.8 # (float) Association similarity threshold (IoU/cost); tune with detector quality
fuse_score: True # (bool) Fuse detection score with motion/IoU for matching; stabilizes weak detections

# BoT-SORT specifics
gmc_method: sparseOptFlow # (str) Global motion compensation: sparseOptFlow|orb|none; helps moving camera scenes

# ReID model related thresh
proximity_thresh: 0.5 # (float) Min IoU to consider tracks proximate for ReID; higher is stricter
appearance_thresh: 0.85 # (float) Min appearance similarity for ReID; raise to avoid identity swaps
with_reid: True # (bool) Enable ReID model use; needs extra model and compute
model: "models/yolo11n-cls.pt" # (str) ReID model name/path; "auto" uses detector features if available


#
#tracker_type: botsort  # (do not modify)
#
## --- General tracking thresholds ---
#track_high_thresh: 0.45     # Higher = cleaner matches (ignore weak detections)
#track_low_thresh: 0.15      # Helps recover temporarily lost IDs
#new_track_thresh: 0.20      # Confidence threshold for spawning new tracks
#track_buffer: 60            # Frames to keep lost tracks; increases persistence across occlusion
#match_thresh: 0.85           # IoU similarity threshold; lower = more forgiving, higher = stricter
#fuse_score: True            # Fuse detection & motion scores for stability
#
## --- BoT-SORT specifics ---
#gmc_method: sparseOptFlow   # (str) Global motion compensation: sparseOptFlow|orb|none; helps moving camera scenes
#
## --- ReID (appearance-based) configuration ---
#with_reid: True             # Enable ReID to maintain identity through occlusions
#model: auto
#proximity_thresh: 0.5       # IoU threshold before checking appearance (default okay)
#appearance_thresh: 0.65     # Lowered slightly to help reconnect briefly lost IDs

# --- Optional fine-tuning parameters ---
# You can experiment with these if ID swaps persist
# min_box_area: 100         # Ignore very small detections (noise)
# max_time_lost: 60         # Alternative way to control persistence duration

